"""add update_date column to note

Revision ID: 624ca485e845
Revises: fb041a9b2404
Create Date: 2026-03-14 11:04:50.796931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '624ca485e845'
down_revision: Union[str, Sequence[str], None] = 'fb041a9b2404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'updated_at')
    # ### end Alembic commands ###
