"""initial

Revision ID: 7198bf160532
Revises: 571efc28c608
Create Date: 2025-11-22 15:57:37.106363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7198bf160532'
down_revision: Union[str, Sequence[str], None] = '571efc28c608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'note', 'user', ['user_id'], ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.drop_column('note', 'user_id')
    # ### end Alembic commands ###
